"""citizens table

Revision ID: 1a3d025065ff
Revises: 
Create Date: 2018-10-20 17:14:43.470150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3d025065ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('is_mobile', sa.Boolean(), nullable=True),
    sa.Column('is_safe', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location'], ['location.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_email'), 'citizen', ['email'], unique=True)
    op.create_index(op.f('ix_citizen_phone_number'), 'citizen', ['phone_number'], unique=True)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_contact', sa.Integer(), nullable=True),
    sa.Column('last_contact', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['main_contact'], ['citizen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party_supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('supply_id', sa.Integer(), nullable=True),
    sa.Column('have', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supply.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_name'), 'supply', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supply_name'), table_name='supply')
    op.drop_table('supply')
    op.drop_table('party_supply')
    op.drop_table('party')
    op.drop_table('location')
    op.drop_index(op.f('ix_citizen_phone_number'), table_name='citizen')
    op.drop_index(op.f('ix_citizen_email'), table_name='citizen')
    op.drop_table('citizen')
    # ### end Alembic commands ###
